"""add instagram posts

Revision ID: 54233bee0fdb
Revises: bfddf1cba386
Create Date: 2026-04-12 17:54:58.437737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54233bee0fdb'
down_revision: Union[str, None] = 'bfddf1cba386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_posts',
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('source_mcp_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.Enum('ES', 'EN', 'BILINGUAL', name='instagram_post_language'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'SCHEDULED', 'PUBLISHED', 'REJECTED', name='instagram_post_status'), nullable=False),
    sa.Column('format', sa.Enum('SINGLE_IMAGE', 'CAROUSEL', name='instagram_post_format'), nullable=False),
    sa.Column('slide_count', sa.SmallInteger(), nullable=False),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('mentions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('post_angle', sa.Enum('INSPIRATIONAL', 'PRACTICAL_TIP', 'LIST', 'STORYTELLING', name='instagram_post_angle'), nullable=True),
    sa.Column('best_publish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('instagram_post_id', sa.String(length=64), nullable=True),
    sa.Column('publish_attempts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('slide_count BETWEEN 1 AND 10', name='ck_instagram_post_slide_count'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_posts_status'), 'instagram_posts', ['status'], unique=False)
    op.create_table('instagram_post_slides',
    sa.Column('instagram_post_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('image_source', sa.Enum('AI_GENERATED', 'STOCK', 'MCP_ASSET', 'USER_UPLOAD', name='instagram_image_source'), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('overlay_text', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instagram_post_id'], ['instagram_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_post_id', 'order', name='uq_instagram_post_slide_order')
    )
    op.create_table('instagram_post_translations',
    sa.Column('instagram_post_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('first_comment', sa.Text(), nullable=True),
    sa.Column('engagement_hook', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instagram_post_id'], ['instagram_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_post_id', 'locale', name='uq_instagram_post_translation_locale')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instagram_post_translations')
    op.drop_table('instagram_post_slides')
    op.drop_index(op.f('ix_instagram_posts_status'), table_name='instagram_posts')
    op.drop_table('instagram_posts')
    # Drop enum types created by this migration
    sa.Enum(name='instagram_post_language').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='instagram_post_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='instagram_post_format').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='instagram_image_source').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='instagram_post_angle').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
